spring:
  application:
    name: gateway-server-route
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: gateway-server-rest
        uri: lb://GATEWAY-SERVER-REST
        predicates:
          - Path=/demo/**
        filters:
          - StripPrefix=1
          - RequestTime=true
server:
  port: 9602
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9600/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug      