spring:
  application:
    name: gateway-predicate
  profiles:
    active: query_route
server:
  port: 9001
  
---
spring:
  profiles: after_route
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://httpbin.org:80/get
          predicates:
          - After=2017-01-20T17:42:47.789-07:00[America/Denver]

---
spring:
  profiles: header_route
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://httpbin.org:80/get
          predicates:
          - Header=X-Request-Id, \d+

---
spring:
  profiles: cookie_route
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80/get
          predicates:
          - Cookie=locale, zh

---
spring:
  profiles: host_route
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://httpbin.org:80/get
          predicates:
          - Host=**:9001

---
spring:
  profiles: method_route
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: http://httpbin.org:80/get
          predicates:
          - Method=GET

#http://127.0.0.1:9001/image/png
---
spring:
  profiles: path_route
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://httpbin.org:80/get
          predicates:
          - Path=/image/{segment}

---
spring:
  profiles: query_route
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: http://httpbin.org:80/get
          predicates:
          - Query=foo, ba.